"""Auto migration

Revision ID: 32ac394cb0f6
Revises: 234123af877e
Create Date: 2021-01-18 17:37:41.444615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ac394cb0f6'
down_revision = '234123af877e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_field', 'counted_character',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='dwh_development_analytic')
    op.alter_column('dim_field', 'is_sub_field',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='dwh_development_analytic')
    op.alter_column('dim_field', 'name',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='dwh_development_analytic')
    op.alter_column('dim_field', 'project_id',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='dwh_development_analytic')
    op.create_index(op.f('ix_dwh_development_analytic_dim_field_field_key'), 'dim_field', ['field_key'], unique=False, schema='dwh_development_analytic')
    op.drop_column('fact_data_extraction', 'project_name', schema='dwh_development_analytic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_data_extraction', sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='dwh_development_analytic')
    op.drop_index(op.f('ix_dwh_development_analytic_dim_field_field_key'), table_name='dim_field', schema='dwh_development_analytic')
    op.alter_column('dim_field', 'project_id',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='dwh_development_analytic')
    op.alter_column('dim_field', 'name',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='dwh_development_analytic')
    op.alter_column('dim_field', 'is_sub_field',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='dwh_development_analytic')
    op.alter_column('dim_field', 'counted_character',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='dwh_development_analytic')
    # ### end Alembic commands ###
