"""Auto migration

Revision ID: 7f29b71f7199
Revises: a3c406bf6c6d
Create Date: 2021-01-18 11:08:32.286544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f29b71f7199'
down_revision = 'a3c406bf6c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('control_type', sa.String(length=255), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('counted_character', sa.Boolean(), nullable=False),
    sa.Column('is_sub_field', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dwh_development_analytic'
    )
    op.create_index(op.f('ix_dwh_development_analytic_dim_field_id'), 'dim_field', ['id'], unique=False, schema='dwh_development_analytic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dwh_development_analytic_dim_field_id'), table_name='dim_field', schema='dwh_development_analytic')
    op.drop_table('dim_field', schema='dwh_development_analytic')
    # ### end Alembic commands ###
