"""Auto migration

Revision ID: 819ec7d72843
Revises: 7f29b71f7199
Create Date: 2021-01-18 13:09:28.272525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819ec7d72843'
down_revision = '7f29b71f7199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_process',
    sa.Column('process_key', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('step', sa.String(length=255), nullable=True),
    sa.Column('sub_step', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('process_key'),
    schema='dwh_development_analytic'
    )
    op.create_index(op.f('ix_dwh_development_analytic_dim_process_process_key'), 'dim_process', ['process_key'], unique=False, schema='dwh_development_analytic')
    op.add_column('dim_field', sa.Column('field_key', sa.Integer(), nullable=False), schema='dwh_development_analytic')
    op.create_index(op.f('ix_dwh_development_analytic_dim_field_field_key'), 'dim_field', ['field_key'], unique=False, schema='dwh_development_analytic')
    op.drop_index('ix_dwh_development_analytic_dim_field_id', table_name='dim_field', schema='dwh_development_analytic')
    op.drop_column('dim_field', 'id', schema='dwh_development_analytic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_field', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dwh_development_analytic.dim_field_id_seq'::regclass)"), autoincrement=True, nullable=False), schema='dwh_development_analytic')
    op.create_index('ix_dwh_development_analytic_dim_field_id', 'dim_field', ['id'], unique=False, schema='dwh_development_analytic')
    op.drop_index(op.f('ix_dwh_development_analytic_dim_field_field_key'), table_name='dim_field', schema='dwh_development_analytic')
    op.drop_column('dim_field', 'field_key', schema='dwh_development_analytic')
    op.drop_index(op.f('ix_dwh_development_analytic_dim_process_process_key'), table_name='dim_process', schema='dwh_development_analytic')
    op.drop_table('dim_process', schema='dwh_development_analytic')
    # ### end Alembic commands ###
