"""Auto migration

Revision ID: 9fa884920d86
Revises: 
Create Date: 2021-01-18 10:59:34.301530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa884920d86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_project_variable',
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('docs_collection_name', sa.String(length=255), nullable=True),
    sa.Column('trans_collection_name', sa.String(length=255), nullable=True),
    sa.Column('performance_collection_name', sa.String(length=255), nullable=True),
    sa.Column('field_collection_name', sa.String(length=255), nullable=True),
    sa.Column('docs_query', sa.String(length=500), nullable=True),
    sa.Column('trans_query', sa.String(length=500), nullable=True),
    sa.Column('performance_query', sa.String(length=500), nullable=True),
    sa.Column('field_query', sa.String(length=500), nullable=True),
    sa.Column('project_backup_dir', sa.String(length=255), nullable=True),
    sa.Column('project_docs_dir', sa.String(length=255), nullable=True),
    sa.Column('project_trans_dir', sa.String(length=255), nullable=True),
    sa.Column('project_performance_dir', sa.String(length=255), nullable=False),
    sa.Column('backup_file_type', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('schedule_date_key', sa.Integer(), nullable=True),
    sa.Column('sechedule_time_key', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    schema='dwh_development_analytic'
    )
    op.create_index(op.f('ix_dwh_development_analytic_dim_project_variable_project_id'), 'dim_project_variable', ['project_id'], unique=False, schema='dwh_development_analytic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dwh_development_analytic_dim_project_variable_project_id'), table_name='dim_project_variable', schema='dwh_development_analytic')
    op.drop_table('dim_project_variable', schema='dwh_development_analytic')
    # ### end Alembic commands ###
