"""Auto migration

Revision ID: a3c406bf6c6d
Revises: 9fa884920d86
Create Date: 2021-01-18 11:01:05.453892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c406bf6c6d'
down_revision = '9fa884920d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
