"""Auto migration

Revision ID: fc6b63bc155a
Revises: 819ec7d72843
Create Date: 2021-01-18 13:10:13.233733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6b63bc155a'
down_revision = '819ec7d72843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_data_extraction',
    sa.Column('data_extraction_key', sa.BigInteger(), nullable=False),
    sa.Column('document_key', sa.BigInteger(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('ori_document_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('doc_set_id', sa.String(length=255), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_time_key', sa.Integer(), nullable=True),
    sa.Column('last_modified_date_key', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('process_key', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_value', sa.String(length=255), nullable=True),
    sa.Column('last_modified_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('data_extraction_key'),
    schema='dwh_development_analytic'
    )
    op.create_index(op.f('ix_dwh_development_analytic_fact_data_extraction_data_extraction_key'), 'fact_data_extraction', ['data_extraction_key'], unique=False, schema='dwh_development_analytic')
    op.create_index(op.f('ix_dwh_development_analytic_fact_data_extraction_document_key'), 'fact_data_extraction', ['document_key'], unique=False, schema='dwh_development_analytic')
    op.create_table('fact_document',
    sa.Column('document_key', sa.BigInteger(), nullable=False),
    sa.Column('ori_document_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('doc_set_id', sa.String(length=255), nullable=True),
    sa.Column('import_time_key', sa.Integer(), nullable=True),
    sa.Column('import_date_key', sa.Integer(), nullable=True),
    sa.Column('export_time_key', sa.Integer(), nullable=True),
    sa.Column('export_date_key', sa.Integer(), nullable=True),
    sa.Column('import_timestamp', sa.DateTime(), nullable=True),
    sa.Column('export_timestamp', sa.DateTime(), nullable=False),
    sa.Column('remark_code', sa.String(length=255), nullable=True),
    sa.Column('remark_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('document_key'),
    schema='dwh_development_analytic'
    )
    op.create_index(op.f('ix_dwh_development_analytic_fact_document_document_key'), 'fact_document', ['document_key'], unique=False, schema='dwh_development_analytic')
    op.create_table('fact_etl_report',
    sa.Column('report_key', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.String(length=255), nullable=False),
    sa.Column('schedule_time_key', sa.String(length=255), nullable=True),
    sa.Column('schedule_date_key', sa.Integer(), nullable=True),
    sa.Column('executor_date_timestamp', sa.DateTime(), nullable=True),
    sa.Column('executor_date_key', sa.Integer(), nullable=True),
    sa.Column('executor_time_key', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('total_time_run_second', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('report_key'),
    schema='dwh_development_analytic'
    )
    op.create_index(op.f('ix_dwh_development_analytic_fact_etl_report_report_key'), 'fact_etl_report', ['report_key'], unique=False, schema='dwh_development_analytic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dwh_development_analytic_fact_etl_report_report_key'), table_name='fact_etl_report', schema='dwh_development_analytic')
    op.drop_table('fact_etl_report', schema='dwh_development_analytic')
    op.drop_index(op.f('ix_dwh_development_analytic_fact_document_document_key'), table_name='fact_document', schema='dwh_development_analytic')
    op.drop_table('fact_document', schema='dwh_development_analytic')
    op.drop_index(op.f('ix_dwh_development_analytic_fact_data_extraction_document_key'), table_name='fact_data_extraction', schema='dwh_development_analytic')
    op.drop_index(op.f('ix_dwh_development_analytic_fact_data_extraction_data_extraction_key'), table_name='fact_data_extraction', schema='dwh_development_analytic')
    op.drop_table('fact_data_extraction', schema='dwh_development_analytic')
    # ### end Alembic commands ###
